// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsz6SosXncN20Aeor0pGAHDEmzhqmR-2c',
    appId: '1:212365129831:web:bd22dea578e7963d0bfcc2',
    messagingSenderId: '212365129831',
    projectId: 'seoul-chukje',
    authDomain: 'seoul-chukje.firebaseapp.com',
    storageBucket: 'seoul-chukje.appspot.com',
    measurementId: 'G-C78QPBN077',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmG2J5PGoOfT2iHVN5ExfmK6TBEg-0W-w',
    appId: '1:212365129831:android:3628bcf1cbc353430bfcc2',
    messagingSenderId: '212365129831',
    projectId: 'seoul-chukje',
    storageBucket: 'seoul-chukje.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0pwHTZqfLKejL7wicTiWvnOPUNPyFDSg',
    appId: '1:212365129831:ios:c69c5773cc34593d0bfcc2',
    messagingSenderId: '212365129831',
    projectId: 'seoul-chukje',
    storageBucket: 'seoul-chukje.appspot.com',
    iosBundleId: 'com.example.sagomap',
  );
}
